package com.zncm.dminter.funvideo.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.zncm.dminter.funvideo.data.VideoModel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "VIDEO_MODEL".
*/
public class VideoModelDao extends AbstractDao<VideoModel, Long> {

    public static final String TABLENAME = "VIDEO_MODEL";

    /**
     * Properties of entity VideoModel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Tag = new Property(2, String.class, "tag", false, "TAG");
        public final static Property Desc = new Property(3, String.class, "desc", false, "DESC");
        public final static Property Url = new Property(4, String.class, "url", false, "URL");
        public final static Property Like = new Property(5, int.class, "like", false, "LIKE");
        public final static Property Type = new Property(6, int.class, "type", false, "TYPE");
        public final static Property Ex1 = new Property(7, String.class, "ex1", false, "EX1");
        public final static Property Ex2 = new Property(8, String.class, "ex2", false, "EX2");
        public final static Property Ex3 = new Property(9, String.class, "ex3", false, "EX3");
        public final static Property Ex4 = new Property(10, String.class, "ex4", false, "EX4");
        public final static Property Ex5 = new Property(11, String.class, "ex5", false, "EX5");
        public final static Property Exi1 = new Property(12, int.class, "exi1", false, "EXI1");
        public final static Property Exi2 = new Property(13, int.class, "exi2", false, "EXI2");
        public final static Property Exi3 = new Property(14, int.class, "exi3", false, "EXI3");
        public final static Property Exi4 = new Property(15, int.class, "exi4", false, "EXI4");
        public final static Property Exi5 = new Property(16, int.class, "exi5", false, "EXI5");
    }


    public VideoModelDao(DaoConfig config) {
        super(config);
    }
    
    public VideoModelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"VIDEO_MODEL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"TAG\" TEXT," + // 2: tag
                "\"DESC\" TEXT," + // 3: desc
                "\"URL\" TEXT," + // 4: url
                "\"LIKE\" INTEGER NOT NULL ," + // 5: like
                "\"TYPE\" INTEGER NOT NULL ," + // 6: type
                "\"EX1\" TEXT," + // 7: ex1
                "\"EX2\" TEXT," + // 8: ex2
                "\"EX3\" TEXT," + // 9: ex3
                "\"EX4\" TEXT," + // 10: ex4
                "\"EX5\" TEXT," + // 11: ex5
                "\"EXI1\" INTEGER NOT NULL ," + // 12: exi1
                "\"EXI2\" INTEGER NOT NULL ," + // 13: exi2
                "\"EXI3\" INTEGER NOT NULL ," + // 14: exi3
                "\"EXI4\" INTEGER NOT NULL ," + // 15: exi4
                "\"EXI5\" INTEGER NOT NULL );"); // 16: exi5
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"VIDEO_MODEL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, VideoModel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String tag = entity.getTag();
        if (tag != null) {
            stmt.bindString(3, tag);
        }
 
        String desc = entity.getDesc();
        if (desc != null) {
            stmt.bindString(4, desc);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(5, url);
        }
        stmt.bindLong(6, entity.getLike());
        stmt.bindLong(7, entity.getType());
 
        String ex1 = entity.getEx1();
        if (ex1 != null) {
            stmt.bindString(8, ex1);
        }
 
        String ex2 = entity.getEx2();
        if (ex2 != null) {
            stmt.bindString(9, ex2);
        }
 
        String ex3 = entity.getEx3();
        if (ex3 != null) {
            stmt.bindString(10, ex3);
        }
 
        String ex4 = entity.getEx4();
        if (ex4 != null) {
            stmt.bindString(11, ex4);
        }
 
        String ex5 = entity.getEx5();
        if (ex5 != null) {
            stmt.bindString(12, ex5);
        }
        stmt.bindLong(13, entity.getExi1());
        stmt.bindLong(14, entity.getExi2());
        stmt.bindLong(15, entity.getExi3());
        stmt.bindLong(16, entity.getExi4());
        stmt.bindLong(17, entity.getExi5());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, VideoModel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String tag = entity.getTag();
        if (tag != null) {
            stmt.bindString(3, tag);
        }
 
        String desc = entity.getDesc();
        if (desc != null) {
            stmt.bindString(4, desc);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(5, url);
        }
        stmt.bindLong(6, entity.getLike());
        stmt.bindLong(7, entity.getType());
 
        String ex1 = entity.getEx1();
        if (ex1 != null) {
            stmt.bindString(8, ex1);
        }
 
        String ex2 = entity.getEx2();
        if (ex2 != null) {
            stmt.bindString(9, ex2);
        }
 
        String ex3 = entity.getEx3();
        if (ex3 != null) {
            stmt.bindString(10, ex3);
        }
 
        String ex4 = entity.getEx4();
        if (ex4 != null) {
            stmt.bindString(11, ex4);
        }
 
        String ex5 = entity.getEx5();
        if (ex5 != null) {
            stmt.bindString(12, ex5);
        }
        stmt.bindLong(13, entity.getExi1());
        stmt.bindLong(14, entity.getExi2());
        stmt.bindLong(15, entity.getExi3());
        stmt.bindLong(16, entity.getExi4());
        stmt.bindLong(17, entity.getExi5());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public VideoModel readEntity(Cursor cursor, int offset) {
        VideoModel entity = new VideoModel( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // tag
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // desc
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // url
            cursor.getInt(offset + 5), // like
            cursor.getInt(offset + 6), // type
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // ex1
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // ex2
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // ex3
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // ex4
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // ex5
            cursor.getInt(offset + 12), // exi1
            cursor.getInt(offset + 13), // exi2
            cursor.getInt(offset + 14), // exi3
            cursor.getInt(offset + 15), // exi4
            cursor.getInt(offset + 16) // exi5
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, VideoModel entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTag(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDesc(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setUrl(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setLike(cursor.getInt(offset + 5));
        entity.setType(cursor.getInt(offset + 6));
        entity.setEx1(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setEx2(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setEx3(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setEx4(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setEx5(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setExi1(cursor.getInt(offset + 12));
        entity.setExi2(cursor.getInt(offset + 13));
        entity.setExi3(cursor.getInt(offset + 14));
        entity.setExi4(cursor.getInt(offset + 15));
        entity.setExi5(cursor.getInt(offset + 16));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(VideoModel entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(VideoModel entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(VideoModel entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
